DROP TABLE IF EXISTS CivilServices_CSID_HID_S;
DROP TABLE IF EXISTS CivilServices_CSID_PN;
DROP TABLE IF EXISTS CivilServices_HID_HS_HZ;
DROP TABLE IF EXISTS CivilServices_HZ_HC;
DROP TABLE IF EXISTS Projects_PID_PN;
DROP TABLE IF EXISTS Projects_SID_SN;
DROP TABLE IF EXISTS Projects_ID_MID;
DROP TABLE IF EXISTS Projects_MID_MN;
DROP TABLE IF EXISTS Citizen_CID;
DROP TABLE IF EXISTS Citizen_CZ_CL;
DROP TABLE IF EXISTS Coffees_DID_DN_DS;
DROP TABLE IF EXISTS Coffees_CID_CN_CC;
DROP TABLE IF EXISTS Coffees_DID_HID;
DROP TABLE IF EXISTS Coffees_DID_CID;

-- CIVIL SERVICES

CREATE TABLE CivilServices_HZ_HC(
    HZ INTEGER NOT NULL,
    HC CHARACTER VARYING NOT NULL,
    PRIMARY KEY (HZ)
);

CREATE TABLE CivilServices_CSID_HID_S(
    CSID INTEGER NOT NULL,
    HID INTEGER NOT NULL,
    S INTEGER NOT NULL,
    PRIMARY KEY (CSID, HID)
);

CREATE TABLE CivilServices_CSID_PN(
    CSID INTEGER NOT NULL,
    PN CHARACTER VARYING NOT NULL,
    PRIMARY KEY (CSID)
);

CREATE TABLE CivilServices_HID_HS_HZ(
    HID INTEGER NOT NULL,
    HS CHARACTER VARYING NOT NULL,
    HZ INTEGER NOT NULL,
    PRIMARY KEY (HID),
    FOREIGN KEY (HZ) REFERENCES CivilServices_HZ_HC (HZ)
);

-- PROJECTS

CREATE TABLE Projects_PID_PN(
    PID INTEGER NOT NULL,
    PN CHARACTER VARYING NOT NULL,
    PRIMARY KEY (PID)
);

CREATE TABLE Projects_SID_SN(
    SID INTEGER NOT NULL,
    SN CHARACTER VARYING NOT NULL,
    PRIMARY KEY (SID)
);

CREATE TABLE Projects_MID_MN(
    MID INTEGER NOT NULL,
    MN CHARACTER VARYING NOT NULL,
    PRIMARY KEY (MID)
);

CREATE TABLE Projects_ID_MID(
    ID INTEGER NOT NULL,
    MID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (MID) REFERENCES Projects_MID_MN (MID)
);

-- CITIZENS

CREATE TABLE Citizens_CID_CN_CS_CNr_CZ_EID (
    CID INTEGER NOT NULL,
    CN CHARACTER VARYING NOT NULL,
    CS CHARACTER VARYING NOT NULL, 
    CNr INTEGER NOT NULL,
    CZ INTEGER NOT NULL,
    EID INTEGER NOT NULL
);

CREATE TABLE Citizens_CZ_CL (
    CZ INTEGER NOT NULL, 
    CL CHARACTER VARYING NOT NULL
);

-- COFFEES

CREATE TABLE Coffees_DID_DN_DS(
    DID INTEGER NOT NULL,
    DN CHARACTER VARYING NOT NULL,
    DS CHARACTER VARYING NOT NULL,
    PRIMARY KEY (DID)
);

CREATE TABLE Coffees_CID_CN_CC(
    CID INTEGER NOT NULL,
    CN CHARACTER VARYING NOT NULL,
    CC CHARACTER VARYING NOT NULL,
    PRIMARY KEY (CID)
);

CREATE TABLE Coffees_DID_HID(
     DID INTEGER NOT NULL,
     HID INTEGER NOT NULL,
     PRIMARY KEY (DID, HID)
);

CREATE TABLE Coffees_DID_CID(
    DID INTEGER NOT NULL,
    CID INTEGER NOT NULL,
    PRIMARY KEY (DID, CID)
);
