
-- CIVIL SERVICES

CREATE TABLE CivilServices_HZ_HC(
    HZ INTEGER NOT NULL,
    HC CHARACTER VARYING NOT NULL,
    PRIMARY KEY (HZ)
);

CREATE TABLE CivilServices_CSID_HID_S(
    CSID INTEGER NOT NULL,
    HID INTEGER NOT NULL,
    S INTEGER NOT NULL,
    PRIMARY KEY (CSID)
);

CREATE TABLE CivilServices_CSID_PN(
    CSID INTEGER NOT NULL,
    PN CHARACTER VARYING NOT NULL,
    PRIMARY KEY (CSID)
);

CREATE TABLE CivilServices_HID_HS_HZ(
    HID INTEGER NOT NULL,
    HS CHARACTER VARYING NOT NULL,
    HZ INTEGER NOT NULL,
    PRIMARY KEY (HID),
    FOREIGN KEY (HZ) REFERENCES CivilServices_HZ_HC (HZ)
);

-- PROJECTS

CREATE TABLE Projects_PID_PN(
    PID INTEGER NOT NULL,
    PN CHARACTER VARYING NOT NULL,
    PRIMARY KEY (PID)
);

CREATE TABLE Projects_SID_SN(
    SID INTEGER NOT NULL,
    SN CHARACTER VARYING NOT NULL,
    PRIMARY KEY (SID)
);

CREATE TABLE Projects_ID_MID(
    ID INTEGER NOT NULL,
    MID INTEGER NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (MID)
);

CREATE TABLE Projects_MID_MN(
    MID INTEGER NOT NULL,
    MN CHARACTER VARYING NOT NULL,
    PRIMARY KEY (MID)
);

-- CITIZENS

CREATE TABLE Citizen_CID (
    CID INTEGER NOT NULL,
    CN CHARACTER VARYING NOT NULL,
    CS CHARACTER VARYING NOT NULL, 
    CNr INTEGER NOT NULL,
    CZ INTEGER NOT NULL,
    EID INTEGER NOT NULL,
);

CREATE TABLE Citizen_CZ_CL (
    CZ INTEGER NOT NULL, 
    CL CHARACTER VARYING NOT NULL,
);

-- COFFEES

CREATE TABLE