-- CivilServices

INSERT INTO CivilService_CSID_PN
SELECT DISTINCT CSID, PN
FROM CivilService;

INSERT INTO CivilService_HID_HS_HZ
SELECT DISTINCT HID, HS, HZ
FROM CivilService;

INSERT INTO CivilService_CSID_HID_S
SELECT DISTINCT CSID, HID, S 
FROM CivilService;

INSERT INTO CivilService_HZ_HC
SELECT DISTINCT HZ, HC 
FROM CivilService;

-- Projects

INSERT INTO Projects_PID_PN
SELECT DISTINCT PID, PN
FROM Projects;

INSERT INTO Projects_SID_SN
SELECT DISTINCT SID, SN
FROM Projects;

INSERT INTO Projects_ID_MID
SELECT DISTINCT ID, MID 
FROM Projects;

INSERT INTO Projects_MID_MN
SELECT DISTINCT MID, MN
FROM Projects;

INSERT INTO Projects_PID_PN
SELECT DISTINCT PID, PN
FROM Projects;

-- Citizens

INSERT INTO Citizens_CID
SELECT DISTINCT CID, CN, CS, CNr, CZ, EID
FROM Citizens;

INSERT INTO Citizens_CZ_CL
SELECT DISTINCT CZ, CL 
FROM Citizens

-- Coffees

INSERT INTO Coffees_DID_DN_DS
SELECT DISTINCT DID, DN, DS  
FROM Coffees

INSERT INTO Coffees_CID_CN_CC
SELECT DISTINCT CID, CN, CC  
FROM Coffees

INSERT INTO Coffees_DID_HID_CID
SELECT DISTINCT DID, HID, CID   
FROM Coffees